spring:
  application:
    name: nebulamind-kb
  profiles:
    active: dev

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0